(add-to-list 'load-path (concat dotfiles-dir "others/ecb"))

;; (load-file (concat dotfiles-dir "cedet/common/cedet.el"))
;; (load-file (concat dotfiles-dir "nxhtml/autostart.el"))
;; (load-file (concat dotfiles-dir "sinatra_el/sinatra.el"))
(require 'ecb)
(setq semantic-load-turn-useful-things-on t)
(setq ecb-tip-of-the-day nil)
(setq ecb-primary-secondary-mouse-buttons (quote mouse-1--mouse-2))
(setq ecb-tip-of-the-day nil)
(setq ecb-tree-buffer-style (quote image))
(setq ecb-tree-indent 4)
(setq ecb-windows-height 0.5)
(setq ecb-windows-width 0.15)
(setq semantic-load-turn-useful-things-on t)
;;(require 'semantic-util)
(setq semantic-load-turn-everything-on t)
;;(require 'semantic-load)
(which-function-mode t)
