(define-key ac-mode-map (kbd "M-TAB") 'auto-complete)
;(define-key erc-mode-map (kbd "C-c r") 'reset-erc-track-mode)
(global-set-key "\C-c\C-t" 'random-color-theme)
(global-set-key "\C-c\C-f" 'gnus-summary-mail-forward)
(global-set-key "\C-c\C-y" 'my-term-paste)
(global-set-key "\C-c\C-k" 'term-char-mode)
(global-set-key "\C-c\C-j" 'term-line-mode)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cb" 'org-iswitchb)
(global-set-key "\C-ci" 'org-insert-todo-heading)
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-x t" 'text-translator)
(global-set-key "\M-." 'etags-select-find-tag)
(global-set-key "\M-?" 'etags-select-find-tag-at-point)
(global-set-key "\M-d" 'dedicated-mode)
(global-set-key "\M-i" 'rct-complete-symbol)
(global-set-key "\M-o" 'occur-word-at-point)
;; (global-set-key (kbd "<f9> n") 'planner-goto-today)
;; (global-set-key (kbd "<f9> p") 'muse-publish-this-file)
;; (global-set-key (kbd "<f9> t") 'planner-create-task-from-buffer)
(global-set-key (kbd "C--") 'text-scale-decrease)
(global-set-key (kbd "C-=") 'text-scale-increase)
(global-set-key (kbd "C-c <down>") 'hs-show-all)
(global-set-key (kbd "C-c <left>") 'hs-hide-block)
(global-set-key (kbd "C-c <right>") 'hs-show-block)
(global-set-key (kbd "C-c <space>") 'just-one-space)
(global-set-key (kbd "C-c <up>") 'hs-hide-all)
(global-set-key (kbd "C-c T") 'multi-term-next)
(global-set-key (kbd "C-c r") 'remember)
(global-set-key (kbd "C-c t") 'multi-term)
(global-set-key (kbd "C-h r") 'ri)
(global-set-key (kbd "C-x x") 'xmp)
(global-set-key [(C-M-s)] 'isearch-backward-regexp)
(global-set-key [(control o)] 'other-frame) ; use Ctrl-o to open a (new) file
(global-set-key [(control s)] 'isearch-forward-regexp)
(global-set-key [(control x)(control b)] 'ibuffer)
(global-set-key [(f11)] 'uncomment-region)
(global-set-key [(f12)] 'comment-region)
(global-set-key [(f6)] 'recompile)
(global-set-key [(meta m)] 'menu-bar-mode)
(global-set-key [(meta q)] 'kill-this-buffer)
(global-set-key [(meta t)] 'tool-bar-mode)
(global-set-key [f10] 'google-this)
(global-set-key [f2] 'emms-lastfm-client-play-recommended)
(global-set-key [(f8)]  'myget)
(global-set-key [(f7)]  'myput)
(global-set-key [(f7)]  'toggle-rot13-mode)


(global-set-key [(f5)] 'my-mood-music)
;;(global-set-key [f9] 'mytidy)
(global-unset-key "\C-x\C-z")
(global-unset-key [(control x)(control z)])
(global-unset-key [(control z)])
 ;(global-set-key "\M-x" 'smex)
;; (define-key ac-complete-mode-map "\C-n" 'ac-next)
;; (define-key ac-complete-mode-map "\C-p" 'ac-previous)
;; (global-set-key [(alt j)] 'tabbar-backward)
;; (global-set-key [(alt k)] 'tabbar-forward)
;; (global-set-key [f7] 'org-publish-blog)
;; (local-set-key [f8>] 'wl)
;;(global-set-key "%" 'match-paren)	; vi style paren matching.
;;(global-set-key "\r" nil)
;;(global-set-key (kbd "C-,") 'tabbar-backward-tab)
;;(global-set-key [(control .)] 'tabbar-forward-tab)
;;(global-set-key [(control s)] 'isearch-repeat-forward)
;;(global-set-key [(control s)] 'save-buffer) ; save  with Ctrl-s
;;(global-set-key [(meta 3)] 'lineno-minor-mode)

;;(global-set-key "\M-x" 'smex)
;; (global-set-key [f7] 'skype--open-missed-chat-buffer-command)
;; (global-set-key [f8] 'skype--open-recent-chat-buffer-command)
(add-hook 'message-mode-hook
          (function (lambda()
                      (local-set-key (kbd "<tab>") 'bbdb-complete-name)
                      )))
