(transient-mark-mode 1)
(setq tramp-default-port '5000)
(setq twittering-use-master-password t)
(setq compilation-scroll-output t)
(add-to-list 'load-path (concat dotfiles-dir "mldonkey/"))
(setq zone-when-idle 'false)
(add-to-list 'auto-mode-alist '("\\.mkd" . markdown-mode))
(windmove-default-keybindings 'meta)
;;(load-file (concat dotfiles-dir "NetBSD.el"))
;;(add-to-list 'load-path (concat dotfiles-dir "/3dmaze"))
;;(require '3dmaze)
(setq mouse-autoselect-window t)
(add-hook 'before-save-hook 'delete-trailing-whitespace)
(setq multi-term-program "/usr/bin/zsh")
(setq stack-trace-on-error nil)
;;(folding-mode-add-find-file-hook)
;;(workgroups-mode)

(setq in-the-mood-for "Skinny Puppy")
(load-file (concat dotfiles-dir "elpa/workgroups-0.2.0/workgroups-autoloads.el"))
(load-file (concat dotfiles-dir "elpa/workgroups-0.2.0/workgroups.el"))
(workgroups-mode)
(appt-activate)
(server-start)
(add-to-list 'load-path (concat dotfiles-dir "others/elim/elisp"))
(add-to-list 'load-path (concat dotfiles-dir "others/"))
(load-library "garak")

(autoload 'save-current-configuration "revive" "Save status" t)
(autoload 'resume "revive" "Resume Emacs" t)
(autoload 'wipe "revive" "Wipe Emacs" t)
(setq erc-hide-list '("JOIN" "PART" "QUIT"))

(add-to-list 'auto-mode-alist '("\\.md$" . markdown-mode))

(require 'supergenpass)
